{{ config(materialized="table") }}

SELECT BOM_ID,ALTERNATE_BOM_NUMBER,SOURCE,BOM_TYPE,BOM_STATUS,BOM_BASE_UOM,BOM_BASE_QUANTITY,BOM_EFFECTIVE_FROM,UOM_ID,SOURCE_INSERT_TS,BOM_EFFECTIVE_TO,
       ERP_SITE_CODE,TRIM(SOURCE_ITEM_CODE) AS SOURCE_ITEM_CODE,SOURCE_BOM_CODE,BOM_COUNTER,IS_DELETED,MATERIAL_ID_LOOKUP,PRNTITMNBR
FROM 
(SELECT BOM_ID,ALTERNATE_BOM_NUMBER,SOURCE,BOM_TYPE,BOM_STATUS,BOM_BASE_UOM,BOM_BASE_QUANTITY,BOM_EFFECTIVE_FROM,UOM_ID,SOURCE_INSERT_TS,BOM_EFFECTIVE_TO,
       ERP_SITE_CODE,SOURCE_ITEM_CODE,SOURCE_BOM_CODE,BOM_COUNTER,IS_DELETED,MATERIAL_ID_LOOKUP,PRNTITMNBR,
       ROW_NUMBER() OVER (PARTITION BY BOM_ID,BOM_EFFECTIVE_FROM,BOM_COUNTER,IS_DELETED,BOM_STATUS  ORDER BY BOM_EFFECTIVE_FROM DESC,BOM_EFFECTIVE_TO DESC,BOM_COUNTER DESC) AS RNK 
FROM {{ ref("SAP_TURBO_BOM") }} ) A WHERE RNK=1 AND COALESCE(BOM_ID,'')<>''